
ekf_filter_node:
  ros__parameters:
    frequency: 30.0
    sensor_timeout: 0.1

    two_d_mode: true
    publish_tf: true

    map_frame: utm     # was >> map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: utm   # was >> world_frame: map

    # Wheels Odometry
    odom0: /odometry/wheels_cov
    odom0_config: [true,  true,  false,
                       false, false, true,
                       false, false, false,
                       false, false, true]
    odom0_differential: true  # was >> false
    odom0_relative: true      # was >> false

    # GPS Odometry
    odom1: /odometry/gps
    odom1_config: [true,  true,  false,
                       false, false, true,
                       false, false, false,
                       false, false, true]
    odom1_differential: false
    odom1_relative: false

    # IMU
    imu0: /imu/data_raw
    imu0_config: [false, false, false,
                  true,  true,  true,
                  false, false, false,
                  false, false, false]
    imu0_differential: false
    imu0_remove_gravitational_acceleration: true
