
ekf_filter_node:
  ros__parameters:
    frequency: 30.0
    sensor_timeout: 0.1

    two_d_mode: true
    publish_tf: true

    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    # was >> world_frame: odom
    world_frame: map

    # Wheels Odometry
    odometry0: /odometry/wheels
    odometry0_config: [true,  true,  false,
                       false, false, true,
                       false, false, false,
                       false, false, true]
    odometry0_differential: false
    odometry0_relative: false

    # GPS Odometry
    odometry1: /odometry/gps
    odometry1_config: [true,  true,  false,
                       false, false, true,
                       false, false, false,
                       false, false, true]
    odometry1_differential: false
    odometry1_relative: false

    # IMU
    imu0: /imu/data_raw
    imu0_config: [false, false, false,
                  true,  true,  true,
                  false, false, false,
                  false, false, false]
    imu0_differential: false
    imu0_remove_gravitational_acceleration: true
