navsat_transform_node:
  ros__parameters:
    frequency: 10.0
    delay: 0.0
    magnetic_declination_radians: 0.0
    yaw_offset: 0.0
    zero_altitude: true
    broadcast_utm_transform: true
    publish_filtered_gps: true
    publish_odometry: true
    use_imu_yaw: true
    use_odometry_yaw: false
    use_manual_datum: false
    wait_for_datum: false
    transform_timeout: 0.1

    # Frame IDs
    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    gps_frame: gps_link

    # Topics
    gps_topic: /gps/fix
    imu_topic: /imu/data_raw
    odometry_topic: /odometry/wheels