ekf_filter_node:
  ros__parameters:
    frequency: 30.0
    sensor_timeout: 0.3

    two_d_mode: true
    publish_tf: true

    map_frame: utm
    odom_frame: odom
    base_link_frame: base_link
    world_frame: utm

    # ✅ Use GPS as main position input
    odom0: /odometry/gps
    odom0_config: [true, true, false,
                   false, false, true,
                   false, false, false,
                   false, false, true]
    odom0_differential: false
    odom0_relative: false

    # 🚫 COMMENTED OUT WHEEL ODOM — Not publishing meaningful data
    odom1: /odometry/wheels_cov  # was >> /odometry/wheels, but lacck the covariance data!
    odom1_config: [true, true, false,
                   false, false, true,
                   false, false, false,
                   false, false, true]
    odom1_differential: false
    odom1_relative: false

    # ✅ Use IMU for orientation and angular velocity

    imu0: /imu/data_raw
    imu0_config: [false, false, false,
                  true,  true,  true,
                  false, false, false,
                  false, false, false]
    imu0_differential: false
    imu0_remove_gravitational_acceleration: true
