ekf_filter_node:
  ros__parameters:

    frequency: 30.0
    sensor_timeout: 0.5
    two_d_mode: true
    transform_time_offset: 0.0
    transform_timeout: 0.0
    print_diagnostics: true
    publish_tf: true
    publish_acceleration: false

    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    base_link_frame_output: base_link_output  # <--- explicitly unique!
    world_frame: map

    odom0: /odometry/wheels
    odom0_config: [true, true, false,
                   false, false, true,
                   false, false, false,
                   false, false, false,
                   false, false, false]
    odom0_queue_size: 10
    odom0_differential: false

    imu0: /imu/data_raw
    imu0_config: [false, false, false,
                  true, true, true,
                  false, false, false,
                  false, false, false,
                  false, false, false]
    imu0_queue_size: 10
    imu0_differential: false
    imu0_remove_gravitational_acceleration: true

    use_control: false
