ekf_filter_node:
  ros__parameters:
    frequency: 30.0
    two_d_mode: true
    sensor_timeout: 0.2

    odom0: /odometry/wheels
    odom0_config: [true,true,false,  false,false,true,  false,false,false,  false,false,true,  false,false,false]
    odom0_differential: false
    odom0_relative: false

    imu0: /imu/data_raw
    imu0_config: [false,false,false,  true,true,true,  false,false,false,  false,false,false,  false,false,false]
    imu0_differential: false
    imu0_relative: false

    odom1: /odometry/gps
    odom1_config: [true,true,false,  false,false,true,  false,false,false,  false,false,false,  false,false,false]
    odom1_differential: false
    odom1_relative: false

    world_frame: odom
    odom_frame: odom
    base_link_frame: base_link
    publish_tf: true
    print_diagnostics: true
